CREATE TABLE private.beats (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	beat text NOT NULL,
	beat_short text NULL,
	river_order text NULL,
	upper_lower text NULL,
	CONSTRAINT priv_beats_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_priv_beats_beat ON private.beats USING btree (beat);
CREATE INDEX idx_priv_beats_river_order ON private.beats USING btree (river_order);
CREATE INDEX idx_priv_beats_upper_lower ON private.beats USING btree (upper_lower);
ALTER TABLE private.beats ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE VIEW private.view_members_reserv_and_cr_history_anonymous
AS SELECT vrcs.date,
    vrcs.beat,
    crst.brown_trout_released + crst.brown_trout_retained AS brown_trout,
    crst.grayling,
    crst.comments
   FROM private.view_reservations_confirmed_staging vrcs
     LEFT JOIN private.catch_returns_staging_table crst ON vrcs.date = crst.catch_date AND vrcs.cr_name = crst.rod_name AND vrcs.beat = crst.beat
  WHERE crst.dnf IS DISTINCT FROM true AND crst.guest IS DISTINCT FROM true
  ORDER BY vrcs.date;

CREATE OR REPLACE FUNCTION public.get_private_reserv_cr_hist_anon_data()
 RETURNS TABLE("date" date, beat text, brown_trout int, grayling int, comments text)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'private', 'public'
AS $function$
  SELECT date, beat, brown_trout, grayling, comments FROM private.view_members_reserv_and_cr_history_anonymous;
$function$
;

GRANT EXECUTE ON FUNCTION public.get_private_reserv_cr_hist_anon_data() TO authenticated, anon;