alter table "public"."catch_returns" drop constraint "CatchReturns_pkey";

drop index if exists "public"."CatchReturns_pkey";


  create table "public"."reservation_beats" (
    "id" bigint generated by default as identity not null,
    "beat" text not null,
    "beat_id" bigint
      );



  create table "public"."reservations_confirmed_staging" (
    "id" bigint generated by default as identity not null,
    "date" date not null,
    "resource" text not null,
    "name" text not null,
    "cr_name" text
      );


alter table "public"."beats" alter column "id" set generated by default;

alter table "public"."catch_returns" drop column "ID";

alter table "public"."catch_returns" add column "dnf" boolean default false;

alter table "public"."catch_returns" add column "id" integer generated by default as identity not null;

alter table "public"."catch_returns" alter column "catch_date" set data type date using "catch_date"::date;

alter table "public"."catch_returns" alter column "guest" set data type boolean using "guest"::boolean;

alter table "public"."catch_returns_staging_table" add column "dnf" boolean default false;

alter table "public"."catch_returns_staging_table" alter column "guest" set data type boolean using "guest"::boolean;

alter table "public"."catch_returns_staging_table" alter column "id" set generated by default;

alter table "public"."members" alter column "id" set generated by default;

CREATE UNIQUE INDEX reservation_beats_pkey ON public.reservation_beats USING btree (id);

CREATE UNIQUE INDEX reservations_confirmed_staging_pkey ON public.reservations_confirmed_staging USING btree (id);

CREATE UNIQUE INDEX "CatchReturns_pkey" ON public.catch_returns USING btree (id);

alter table "public"."reservation_beats" add constraint "reservation_beats_pkey" PRIMARY KEY using index "reservation_beats_pkey";

alter table "public"."reservations_confirmed_staging" add constraint "reservations_confirmed_staging_pkey" PRIMARY KEY using index "reservations_confirmed_staging_pkey";

alter table "public"."catch_returns" add constraint "CatchReturns_pkey" PRIMARY KEY using index "CatchReturns_pkey";

grant delete on table "public"."reservation_beats" to "anon";

grant insert on table "public"."reservation_beats" to "anon";

grant references on table "public"."reservation_beats" to "anon";

grant select on table "public"."reservation_beats" to "anon";

grant trigger on table "public"."reservation_beats" to "anon";

grant truncate on table "public"."reservation_beats" to "anon";

grant update on table "public"."reservation_beats" to "anon";

grant delete on table "public"."reservation_beats" to "authenticated";

grant insert on table "public"."reservation_beats" to "authenticated";

grant references on table "public"."reservation_beats" to "authenticated";

grant select on table "public"."reservation_beats" to "authenticated";

grant trigger on table "public"."reservation_beats" to "authenticated";

grant truncate on table "public"."reservation_beats" to "authenticated";

grant update on table "public"."reservation_beats" to "authenticated";

grant delete on table "public"."reservation_beats" to "service_role";

grant insert on table "public"."reservation_beats" to "service_role";

grant references on table "public"."reservation_beats" to "service_role";

grant select on table "public"."reservation_beats" to "service_role";

grant trigger on table "public"."reservation_beats" to "service_role";

grant truncate on table "public"."reservation_beats" to "service_role";

grant update on table "public"."reservation_beats" to "service_role";

grant delete on table "public"."reservations_confirmed_staging" to "anon";

grant insert on table "public"."reservations_confirmed_staging" to "anon";

grant references on table "public"."reservations_confirmed_staging" to "anon";

grant select on table "public"."reservations_confirmed_staging" to "anon";

grant trigger on table "public"."reservations_confirmed_staging" to "anon";

grant truncate on table "public"."reservations_confirmed_staging" to "anon";

grant update on table "public"."reservations_confirmed_staging" to "anon";

grant delete on table "public"."reservations_confirmed_staging" to "authenticated";

grant insert on table "public"."reservations_confirmed_staging" to "authenticated";

grant references on table "public"."reservations_confirmed_staging" to "authenticated";

grant select on table "public"."reservations_confirmed_staging" to "authenticated";

grant trigger on table "public"."reservations_confirmed_staging" to "authenticated";

grant truncate on table "public"."reservations_confirmed_staging" to "authenticated";

grant update on table "public"."reservations_confirmed_staging" to "authenticated";

grant delete on table "public"."reservations_confirmed_staging" to "service_role";

grant insert on table "public"."reservations_confirmed_staging" to "service_role";

grant references on table "public"."reservations_confirmed_staging" to "service_role";

grant select on table "public"."reservations_confirmed_staging" to "service_role";

grant trigger on table "public"."reservations_confirmed_staging" to "service_role";

grant truncate on table "public"."reservations_confirmed_staging" to "service_role";

grant update on table "public"."reservations_confirmed_staging" to "service_role";


