CREATE TABLE private.reservation_beats (
        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
        beat text NOT NULL,
        beat_id int8 NULL,
        CONSTRAINT reservation_beats_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_priv_reservation_beats_beat ON private.reservation_beats USING btree (beat);
ALTER TABLE private.reservation_beats ENABLE ROW LEVEL SECURITY;