CREATE TABLE private.reservations_confirmed_staging (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"date" date NOT NULL,
	resource text NOT NULL,
	"name" text NOT NULL,
	cr_name text NULL,
	CONSTRAINT priv_reservations_confirmed_staging_pkey PRIMARY KEY (id),
	CONSTRAINT uq_priv_reservation_date_cr_name UNIQUE (date, cr_name, resource)
);
CREATE INDEX idx_priv_reservations_confirmed_staging_date ON private.reservations_confirmed_staging USING btree (date);
CREATE INDEX idx_priv_reservations_confirmed_staging_resource ON private.reservations_confirmed_staging USING btree (resource);
ALTER TABLE private.reservations_confirmed_staging ENABLE ROW LEVEL SECURITY;

CREATE TABLE private.catch_returns_staging_table (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"timestamp" text DEFAULT now() NULL,
	rod_name text NULL,
	catch_date date NULL,
	beat text NULL,
	brown_trout_released int4 NULL,
	grayling int4 NULL,
	rainbow_trout int4 NULL,
	other_species int4 NULL,
	brown_trout_retained int4 NULL,
	guest bool NULL,
	"comments" text NULL,
	dnf bool DEFAULT false NOT NULL,
	CONSTRAINT priv_catch_returns_staging_table_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_priv_beat ON private.catch_returns_staging_table USING btree (beat);
CREATE INDEX idx_priv_catch_date ON private.catch_returns_staging_table USING btree (catch_date);
ALTER TABLE private.catch_returns_staging_table ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE VIEW private.view_reservations_confirmed_staging AS 
SELECT  rcs.date,
    	rcs.cr_name,
    	rb.beat_id,
    	bt.beat,
    	bt.river_order,
    	rcs.id,
    	rcs.name
   FROM private.reservations_confirmed_staging rcs
     JOIN reservation_beats rb ON rb.beat = rcs.resource
     JOIN beats bt ON rb.beat_id = bt.id
  ORDER BY rcs.date;

CREATE OR REPLACE VIEW private.view_in_season_dashb_1_count_res_cr AS 
WITH timeline AS (
			SELECT generate_series(
					date_trunc('year'::text, 
								CURRENT_DATE::timestamp with time zone) + '3 mons'::interval, 
								(CURRENT_DATE - 1)::timestamp with time zone, 
								'7 days'::interval)::date AS week_starting), 
	filtered_reservations AS (
	         SELECT vrcs.date,
	            	vrcs.cr_name,
	            	vrcs.beat,
	            	crst."timestamp"
	           FROM private.view_reservations_confirmed_staging vrcs
	             LEFT JOIN private.catch_returns_staging_table crst 
	             			ON vrcs.date = crst.catch_date 
	             				AND vrcs.cr_name = crst.rod_name 
	             				AND vrcs.beat = crst.beat
	          				WHERE crst.dnf IS DISTINCT FROM true AND vrcs.date < CURRENT_DATE AND crst.guest IS DISTINCT FROM true)
 SELECT week_starting,
    ( SELECT count(*) AS count
           FROM filtered_reservations fr
          WHERE fr.date >= t.week_starting AND fr.date < (t.week_starting + 7)) AS reservations,
    ( SELECT count(*) AS count
           FROM filtered_reservations fr
          WHERE fr.date >= t.week_starting AND fr.date < (t.week_starting + 7) AND fr."timestamp" IS NOT NULL) AS catch_returns
   FROM timeline t
  ORDER BY week_starting;

CREATE OR REPLACE FUNCTION public.get_private_dashb_1_data()
 RETURNS TABLE(week_starting date, reservations integer, catch_returns integer)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'private', 'public'
AS $function$
  SELECT week_starting, reservations, catch_returns FROM private.view_in_season_dashb_1_count_res_cr;
$function$
;

drop view public.view_in_season_dashb_1_count_res_cr;