CREATE TABLE private.catch_returns (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	member_name text NULL,
	catch_date date NULL,
	brown_trout int4 NULL,
	brown_trout_killed int4 NULL,
	grayling int4 NULL,
	rainbow_trout int4 NULL,
	other_species int4 NULL,
	guest bool NULL,
	beats_id int4 NULL,
	dnf bool DEFAULT false NULL,
	CONSTRAINT "CatchReturns_pkey" PRIMARY KEY (id)
);
CREATE INDEX idx_priv_catch_returns_beats_id ON private.catch_returns USING btree (beats_id);
CREATE INDEX idx_priv_catch_returns_catch_date ON private.catch_returns USING btree (catch_date);
CREATE INDEX idx_priv_catch_returns_guest ON private.catch_returns USING btree (guest);
CREATE UNIQUE INDEX uq_priv_catch_returns_member_date_only_if_not_guest ON private.catch_returns USING btree (member_name, catch_date) WHERE (guest = false);
ALTER TABLE private.catch_returns ENABLE ROW LEVEL SECURITY;

CREATE TABLE private.reservations_confirmed (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"date" date NOT NULL,
	beats_id int4 NOT NULL,
	members_id int4 NOT NULL,
	CONSTRAINT priv_reservations_confirmed_pkey PRIMARY KEY (id),
	CONSTRAINT uq_priv_reservation_confirmed_date_member_beat UNIQUE (date, members_id, beats_id)
);
CREATE INDEX idx_priv_reservations_confirmed_beat ON private.reservations_confirmed USING btree (beats_id);
CREATE INDEX idx_priv_reservations_confirmed_date ON private.reservations_confirmed USING btree (date);
CREATE INDEX idx_priv_reservations_confirmed_member ON private.reservations_confirmed USING btree (members_id);
ALTER TABLE private.reservations_confirmed ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE VIEW private.view_troutseasondata
AS SELECT c.id,
    c.member_name,
    COALESCE(c.brown_trout, 0) + COALESCE(c.brown_trout_killed, 0) AS brown_trout,
    c.brown_trout_killed,
    c.rainbow_trout,
    c.grayling,
    c.other_species,
    to_char(c.catch_date::timestamp with time zone, 'Mon'::text) AS seasonal_month,
        CASE
            WHEN to_char(c.catch_date::timestamp with time zone, 'MM'::text) >= '04'::text AND to_char(c.catch_date::timestamp with time zone, 'MM'::text) <= '09'::text THEN to_char(c.catch_date::timestamp with time zone, 'YYYY'::text)
            ELSE 'Off-Season'::text
        END AS seasonal_year,
        CASE
            WHEN to_char(c.catch_date::timestamp with time zone, 'MM'::text) >= '04'::text AND to_char(c.catch_date::timestamp with time zone, 'MM'::text) <= '09'::text THEN to_char(c.catch_date::timestamp with time zone, 'YYYY'::text)::integer
            ELSE NULL::integer
        END AS seasonal_year_int,
    c.catch_date,
    b.beat,
    b.beat_short,
    b.river_order,
    b.upper_lower,
    c.guest,
    COALESCE(c.brown_trout, 0) + COALESCE(c.brown_trout_killed, 0) + COALESCE(c.grayling, 0) + COALESCE(c.rainbow_trout, 0) + COALESCE(c.other_species, 0) AS total_fish_caught,
    c.beats_id
   FROM private.catch_returns c
     JOIN beats b ON c.beats_id = b.id
  WHERE c.guest IS FALSE AND c.dnf IS FALSE;

CREATE TABLE private.year_param (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	target_year int4 NULL,
	target_start_date date NULL,
	target_end_date date NULL,
	CONSTRAINT year_param_pkey PRIMARY KEY (id)
);
ALTER TABLE private.year_param ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE VIEW private.report_1_4_freq_browntrout
AS SELECT brown_trout AS catchsize,
    count(*) AS frequency
   FROM private.view_troutseasondata vt
  WHERE seasonal_year_int = (( SELECT year_param.target_year
           FROM private.year_param
         LIMIT 1))
  GROUP BY brown_trout
  ORDER BY brown_trout;

drop view public.report_1_4_freq_browntrout;

CREATE OR REPLACE VIEW private.report_1_4_freq_grayling
AS SELECT grayling AS catchsize,
    count(*) AS frequency
   FROM private.view_troutseasondata vt
  WHERE seasonal_year_int = (( SELECT year_param.target_year
           FROM private.year_param
         LIMIT 1))
  GROUP BY grayling
  ORDER BY grayling;

drop view public.report_1_4_freq_grayling;

CREATE OR REPLACE VIEW private.report_1_4_freq_totalfishcaught
AS SELECT total_fish_caught AS catchsize,
    count(*) AS frequency
   FROM private.view_troutseasondata vt
  WHERE seasonal_year_int = (( SELECT year_param.target_year
           FROM private.year_param
         LIMIT 1))
  GROUP BY total_fish_caught
  ORDER BY total_fish_caught;

drop view public.report_1_4_freq_totalfishcaught;

CREATE OR REPLACE VIEW private.report_1_5_upper_lower_all
AS SELECT seasonal_year,
    round(avg(
        CASE
            WHEN upper_lower = 'Upper'::text THEN total_fish_caught
            ELSE NULL::integer
        END), 1) AS upper_avg,
    round(avg(
        CASE
            WHEN upper_lower = 'Lower'::text THEN total_fish_caught
            ELSE NULL::integer
        END), 1) AS lower_avg
   FROM private.view_troutseasondata vtsd
  WHERE seasonal_year !~~ 'Off%'::text
  GROUP BY seasonal_year
  ORDER BY seasonal_year;

drop view public.report_1_5_upper_lower_all;

CREATE OR REPLACE VIEW private.report_1_5_upper_lower_browntrout
AS SELECT seasonal_year,
    round(avg(
        CASE
            WHEN upper_lower = 'Upper'::text THEN brown_trout
            ELSE NULL::integer
        END), 1) AS upper_avg,
    round(avg(
        CASE
            WHEN upper_lower = 'Lower'::text THEN brown_trout
            ELSE NULL::integer
        END), 1) AS lower_avg
   FROM private.view_troutseasondata vtsd
  WHERE seasonal_year !~~ 'Off%'::text
  GROUP BY seasonal_year
  ORDER BY seasonal_year;

drop view public.report_1_5_upper_lower_browntrout;

CREATE OR REPLACE VIEW private.report_1_5_upper_lower_grayling
AS SELECT seasonal_year,
    round(avg(
        CASE
            WHEN upper_lower = 'Upper'::text THEN grayling
            ELSE NULL::integer
        END), 1) AS upper_avg,
    round(avg(
        CASE
            WHEN upper_lower = 'Lower'::text THEN grayling
            ELSE NULL::integer
        END), 1) AS lower_avg
   FROM private.view_troutseasondata vtsd
  WHERE seasonal_year !~~ 'Off%'::text
  GROUP BY seasonal_year
  ORDER BY seasonal_year;

drop view public.report_1_5_upper_lower_grayling;

CREATE OR REPLACE VIEW private.report_1_6_1_tr_v_gr_ratio_upper_lower
AS SELECT seasonal_year,
    upper_lower,
    sum(brown_trout) AS total_brown_trout,
    sum(grayling) AS total_grayling,
    round(sum(grayling)::numeric * 100.0 / NULLIF(sum(brown_trout) + sum(grayling), 0)::numeric, 1) AS grayling_percentage
   FROM private.view_troutseasondata vtsd
  WHERE seasonal_year !~~ 'Off%'::text AND upper_lower !~~ 'Unk%'::text
  GROUP BY seasonal_year, upper_lower
  ORDER BY seasonal_year;

drop view public.report_1_6_1_tr_v_gr_ratio_upper_lower;

CREATE OR REPLACE VIEW private.report_1_6_2_tr_v_gr_ratio_curr_year_monthly
AS SELECT sum(brown_trout + brown_trout_killed) AS total_brown_trout,
    sum(grayling) AS total_grayling,
    round(sum(grayling)::numeric * 100.0 / NULLIF(sum(brown_trout + brown_trout_killed) + sum(grayling), 0)::numeric, 1) AS grayling_percentage,
    seasonal_month
   FROM private.view_troutseasondata vt
  WHERE seasonal_year_int = (( SELECT year_param.target_year
           FROM private.year_param
         LIMIT 1))
  GROUP BY seasonal_month
  ORDER BY (to_date(seasonal_month, 'Mon'::text));

drop view public.report_1_6_2_tr_v_gr_ratio_curr_year_monthly;

CREATE OR REPLACE VIEW private.report_1_6_2_tr_v_gr_ratio_historical_monthly
AS SELECT sum(brown_trout + brown_trout_killed) AS total_brown_trout,
    sum(grayling) AS total_grayling,
    round(sum(grayling)::numeric * 100.0 / NULLIF(sum(brown_trout + brown_trout_killed) + sum(grayling), 0)::numeric, 1) AS grayling_percentage,
    seasonal_month
   FROM private.view_troutseasondata vt
  WHERE seasonal_year !~~ 'Off%'::text AND seasonal_year_int <> (( SELECT target_year
           FROM private.year_param
         LIMIT 1))
  GROUP BY seasonal_month
  ORDER BY (to_date(seasonal_month, 'Mon'::text));

drop view public.report_1_6_2_tr_v_gr_ratio_historical_monthly;

CREATE OR REPLACE VIEW private.report_1_6_tr_v_gr_ratio
AS SELECT seasonal_year,
    sum(brown_trout) AS total_brown_trout,
    sum(grayling) AS total_grayling,
    round(sum(grayling)::numeric * 100.0 / NULLIF(sum(brown_trout) + sum(grayling), 0)::numeric, 1) AS grayling_percentage
   FROM private.view_troutseasondata vtsd
  WHERE seasonal_year !~~ 'Off%'::text
  GROUP BY seasonal_year
  ORDER BY seasonal_year;

drop view public.report_1_6_tr_v_gr_ratio;

CREATE OR REPLACE VIEW private.report_2_0_num_days_fished_by_beat
AS SELECT beat,
    count(id) AS num_days_fished
   FROM private.view_troutseasondata vtsd
  WHERE seasonal_year_int = (( SELECT target_year
           FROM private.year_param
         LIMIT 1))
  GROUP BY beat, river_order
  ORDER BY river_order;

drop view public.report_2_0_num_days_fished_by_beat;

CREATE OR REPLACE VIEW private.view_reservations_confirmed
AS SELECT rc.id,
    rc.date,
    m.cr_name,
    b.beat,
    b.beat_short,
    b.river_order,
    to_char(rc.date::timestamp with time zone, 'Mon'::text) AS seasonal_month,
        CASE
            WHEN to_char(rc.date::timestamp with time zone, 'MM'::text) >= '04'::text AND to_char(rc.date::timestamp with time zone, 'MM'::text) <= '09'::text THEN to_char(rc.date::timestamp with time zone, 'YYYY'::text)
            ELSE 'Off-Season'::text
        END AS seasonal_year,
        CASE
            WHEN to_char(rc.date::timestamp with time zone, 'MM'::text) >= '04'::text AND to_char(rc.date::timestamp with time zone, 'MM'::text) <= '09'::text THEN to_char(rc.date::timestamp with time zone, 'YYYY'::text)::integer
            ELSE NULL::integer
        END AS seasonal_year_int,
    rc.beats_id,
    rc.members_id,
    m.year_of_membership
   FROM private.reservations_confirmed rc
     JOIN private.members m ON rc.members_id = m.id
     JOIN beats b ON rc.beats_id = b.id
     LEFT JOIN private.catch_returns cr ON rc.date = cr.catch_date AND m.cr_name = cr.member_name AND cr.guest IS DISTINCT FROM true
  WHERE cr.dnf IS DISTINCT FROM true;

CREATE OR REPLACE VIEW private.report_2_0_num_days_fished_by_beat_v2
AS SELECT b.beat_short AS beat,
    count(vrc.id) AS num_days_fished
   FROM public.beats b
     CROSS JOIN ( SELECT target_year
           FROM private.year_param
         LIMIT 1) yp
     LEFT JOIN private.view_reservations_confirmed vrc ON vrc.beats_id = b.id AND vrc.date >= make_date(yp.target_year, 4, 1) AND vrc.date <= make_date(yp.target_year, 9, 30)
     LEFT JOIN private.catch_returns cr ON vrc.date = cr.catch_date AND vrc.cr_name = cr.member_name
  WHERE b.id <> 18 AND cr.dnf IS DISTINCT FROM true AND cr.guest IS DISTINCT FROM true
  GROUP BY b.beat_short, b.river_order
  ORDER BY b.river_order;

drop view public.report_2_0_num_days_fished_by_beat_v2;

CREATE OR REPLACE VIEW private.view_base_catch
AS SELECT b.river_order,
    b.beat,
    b.beat_short,
    c.catch_date,
    COALESCE(c.brown_trout, 0) + COALESCE(c.brown_trout_killed, 0) AS browntrout,
    COALESCE(c.grayling, 0) AS grayling,
    COALESCE(c.brown_trout, 0) + COALESCE(c.brown_trout_killed, 0) + COALESCE(c.grayling, 0) + COALESCE(c.rainbow_trout, 0) + COALESCE(c.other_species, 0) AS totalcaught,
    c.guest,
        CASE
            WHEN to_char(c.catch_date::timestamp with time zone, 'MM'::text) >= '04'::text AND to_char(c.catch_date::timestamp with time zone, 'MM'::text) <= '09'::text THEN to_char(c.catch_date::timestamp with time zone, 'YYYY'::text)
            ELSE 'Off-Season'::text
        END AS seasonalyear,
        CASE
            WHEN to_char(c.catch_date::timestamp with time zone, 'MM'::text) >= '04'::text AND to_char(c.catch_date::timestamp with time zone, 'MM'::text) <= '09'::text THEN to_char(c.catch_date::timestamp with time zone, 'YYYY'::text)::integer
            ELSE NULL::integer
        END AS seasonalyear_int
   FROM private.catch_returns c
     JOIN public.beats b ON c.beats_id = b.id
  WHERE c.guest is distinct from true and c.dnf is distinct from true;

drop view public.view_base_catch;

CREATE OR REPLACE VIEW private.report_2_1_num_days_fished_by_beat_by_month
AS SELECT beat_short,
    river_order,
    seasonal_month,
    count(id) AS num_days_fished
   FROM private.view_troutseasondata vtsd
  WHERE seasonal_year_int = (( SELECT year_param.target_year
           FROM private.year_param
         LIMIT 1))
  GROUP BY beat_short, seasonal_month, river_order
  ORDER BY river_order;

drop view public.report_2_1_num_days_fished_by_beat_by_month;

CREATE OR REPLACE VIEW private.report_2_1_num_days_fished_by_beat_by_month_v2
AS SELECT b.beat_short,
    b.river_order,
    vrc.seasonal_month,
    count(vrc.id) AS num_days_fished
   FROM public.beats b
     CROSS JOIN ( SELECT target_year
           FROM private.year_param
         LIMIT 1) yp
     LEFT JOIN private.view_reservations_confirmed vrc ON vrc.beats_id = b.id AND vrc.date >= make_date(yp.target_year, 4, 1) AND vrc.date <= make_date(yp.target_year, 9, 30)
     LEFT JOIN private.catch_returns cr ON vrc.date = cr.catch_date AND vrc.cr_name = cr.member_name
  WHERE b.id <> 18 AND cr.dnf IS DISTINCT FROM true AND cr.guest IS DISTINCT FROM true
  GROUP BY b.beat_short, vrc.seasonal_month, b.river_order
  ORDER BY b.river_order;

drop view public.report_2_1_num_days_fished_by_beat_by_month_v2;

CREATE OR REPLACE VIEW private.report_2_3_num_days_fished_by_year_v2
AS SELECT year,
    sum(record_count) AS total_count
   FROM ( SELECT vrc.seasonal_year_int AS year,
            count(vrc.id) AS record_count
           FROM private.view_reservations_confirmed vrc
             LEFT JOIN private.view_troutseasondata vt 
             	ON vt.catch_date = vrc.date AND vt.member_name = vrc.cr_name AND vt.seasonal_year_int = vrc.year_of_membership
          GROUP BY vrc.seasonal_year_int
        UNION ALL
         SELECT vt.seasonal_year_int AS year,
            count(*) AS record_count
           FROM private.view_troutseasondata vt
          WHERE vt.beats_id = 18
          GROUP BY vt.seasonal_year_int) combined
  GROUP BY year
  ORDER BY year;

drop view public.report_2_3_num_days_fished__by_year;
drop view public.report_2_3_num_days_fished_by_year_v2;

CREATE OR REPLACE VIEW private.report_2_4_members_zero_reservations_scd
AS WITH year_param AS (
    SELECT target_start_date, target_end_date, target_year
    FROM private.year_param
    LIMIT 1
), date_series AS (
    SELECT generate_series(
               (SELECT target_start_date FROM year_param)::timestamp with time zone,
               LEAST(CURRENT_DATE, (SELECT target_end_date FROM private.year_param))::timestamp with time zone,
               '1 day'::interval
           )::date AS dt
), first_reservation AS (
    SELECT r.members_id,
        min(r.date) AS first_booked_on
    FROM private.reservations_confirmed r
        JOIN private.members m_1 ON m_1.id = r.members_id
    WHERE r.date <= CURRENT_DATE
      AND m_1.year_of_membership = (SELECT target_year FROM year_param)
    GROUP BY r.members_id
), total_members AS (
    SELECT count(*) AS total
    FROM private.members
    WHERE members.year_of_membership = (SELECT target_year FROM year_param)
), members_with_reservation_by_date AS (
    SELECT d.dt,
        count(fr.members_id) AS has_booked
    FROM date_series d
        LEFT JOIN first_reservation fr ON fr.first_booked_on <= d.dt
    GROUP BY d.dt
)
SELECT m.dt AS date,
    tm.total - m.has_booked AS members_without_reservation
FROM members_with_reservation_by_date m
    CROSS JOIN total_members tm
ORDER BY m.dt;

drop view public.report_2_4_members_zero_reservations_scd;

--drop view public.report_1_2_stats_allspecies_bymonthbybeat2;

CREATE OR REPLACE VIEW private.report_1_2_stats_allspecies_bymonthbybeat2
AS SELECT "Beat",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sept"
   FROM ( SELECT b.river_order AS "SortKey",
            b.beat AS "Beat",
            round(avg(
                CASE
                    WHEN vtsd.seasonal_month ~~ 'Apr%'::text THEN vtsd.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "Apr",
            round(avg(
                CASE
                    WHEN vtsd.seasonal_month ~~ 'May%'::text THEN vtsd.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "May",
            round(avg(
                CASE
                    WHEN vtsd.seasonal_month ~~ 'Jun%'::text THEN vtsd.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "Jun",
            round(avg(
                CASE
                    WHEN vtsd.seasonal_month ~~ 'Jul%'::text THEN vtsd.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "Jul",
            round(avg(
                CASE
                    WHEN vtsd.seasonal_month ~~ 'Aug%'::text THEN vtsd.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "Aug",
            round(avg(
                CASE
                    WHEN vtsd.seasonal_month ~~ 'Sep%'::text THEN vtsd.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "Sept"
           FROM beats b
             LEFT JOIN private.view_troutseasondata vtsd ON vtsd.beat = b.beat AND vtsd.seasonal_year_int = (( SELECT target_year
                   FROM private.year_param
                 LIMIT 1))
          WHERE b.beat !~~ '%Not Recorded%'::text
          GROUP BY b.river_order, b.beat
        UNION ALL
         SELECT 'z'::text AS "SortKey",
            'Grand Total (Avg)'::text AS "Beat",
            round(avg(
                CASE
                    WHEN v2.seasonal_month ~~ 'Apr%'::text THEN v2.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "Apr",
            round(avg(
                CASE
                    WHEN v2.seasonal_month ~~ 'May%'::text THEN v2.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "May",
            round(avg(
                CASE
                    WHEN v2.seasonal_month ~~ 'Jun%'::text THEN v2.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "Jun",
            round(avg(
                CASE
                    WHEN v2.seasonal_month ~~ 'Jul%'::text THEN v2.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "Jul",
            round(avg(
                CASE
                    WHEN v2.seasonal_month ~~ 'Aug%'::text THEN v2.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "Aug",
            round(avg(
                CASE
                    WHEN v2.seasonal_month ~~ 'Sep%'::text THEN v2.total_fish_caught
                    ELSE NULL::integer
                END), 1) AS "Sept"
           FROM private.view_troutseasondata v2
          WHERE v2.seasonal_year_int = (( SELECT target_year
                   FROM private.year_param
                 LIMIT 1))) "CombinedStats"
  ORDER BY "SortKey";

  drop table public.year_param;

  drop view public.view_troutseasondata;

  drop view public.view_reservations_confirmed;

  drop table public.catch_returns;

  drop table public.reservations_confirmed;

drop view public.view_secrep_membername_catchreturns_count_operational;
CREATE OR REPLACE VIEW private.view_secrep_membername_catchreturns_count_operational
AS WITH filtered_data AS (
         SELECT vrcs.cr_name,
            crst.catch_date AS has_return
           FROM reservations_confirmed_staging vrcs
             LEFT JOIN catch_returns_staging_table crst ON vrcs.date = crst.catch_date AND vrcs.cr_name = crst.rod_name
          WHERE crst.dnf IS DISTINCT FROM true
        )
 SELECT cr_name,
    count(*) AS reservations_count,
    count(has_return) AS returns_count,
    count(*) - count(has_return) AS variance
   FROM filtered_data
  GROUP BY cr_name
  ORDER BY (count(*)) DESC;
  



